### ISSUE TITLE
[FEATURE REQUEST] - StyleAligned Reference as a model patch rather than a Ksampler

### ISSUE THREAD

**Issue by alessandroperilli** [brianfitzgerald/style_aligned_comfy#6]
First of all, thank you for implementing this very interesting technique. I'm working to include it in the upcoming [AP Workflow 7.0](https://perilli.com/ai/comfyui). 

I am reviewing your second node, `StyleAligned Reference`, and I really wished it'd work more like the original version of the `StyleAligned Batch` node: a patch for the model that would ingest a reference image and return the modified model. 

That implementation would allow me to chain it with other nodes acting as model patches:

<img width="1349" alt="Screenshot 2023-12-13 at 11 17 11" src="https://github.com/brianfitzgerald/style_aligned_comfy/assets/9775949/50f0981a-390d-4f7c-bafe-1d3e2a35c02f">

(ignore the fact that IPAdapter, appearing in this screenshot, is compatible or not with StyleAligned. Like the rest of the model patching chain, it can be bypassed)

That implementation would also allow us to reuse an existing KSampler and, where present, a Refiner. I have both but the current approach makes it a little bit harder integrate.

Is there any chance you'd consider that alternative implementation?

Thank you for considering the suggestion.

**Comment by brianfitzgerald** [comment]
I decided to implement it as a sampler as otherwise the user has to handle some extra logic around processing and noising the batch. Since the DDIM-inverted latent is already noised, it doesn't need more noise applied; however, the rest of the latents in the batch do. Additionally, the reference latent needs to be added to the batch, and then removed when inference is done. Since neither is supported by the existing custom sampler, I had to write a new sampler node.

Additionally - the batch-only node is still available, under the name `StyleAligned Batch Align`, and behaves the same as the `StyleAligned Batch` node. Hope this helps!

**Comment by alessandroperilli** [comment]
I see. My request was specifically about a single image situation, and not a batch. Regardless, I understand now that the mechanics of this technique make it difficult to implement in any other way. Thank you for taking the time to answer.
